version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
    working_directory: ~/eventuate-development
    steps:
      - checkout
      - run:
          command: ./build-and-publish.sh
