name: Build
on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build and publish
        run: ./build-and-publish.sh
